config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.access } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: { registrations: 'devise_override/registrations' }

  root to: 'shows#index'

  resources :shows do
    get :list, on: :collection
    get :change_status, on: :member
    post :to_favorite, on: :member
    resources :comments
  end

  resources :genres

  resources :users do
    get :favorites, on: :member
    get :rates, on: :member
  end

  resources :comments, only: [:create]
  resources :episodes, only: [:new, :show] do
    resources :comments
    post :mark_as_watched, on: :collection
  end

  get :what_to_see, to: 'episodes#what_to_see'
  get :disclaimer, to: 'home#disclaimer'

  post '/rate' => 'rater#create', as: 'rate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, :polymorphic => true
  has_many :comments, as: :commentable
  belongs_to :user

  validates_presence_of :body, :user, :commentable

  def show
    return @show if defined?(@show)
    @post = commentable.is_a?(Show) ? commentable : commentable.show
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :show
  has_many :users_episodes
  has_many :comments, :as => :commentable

  ratyrate_rateable 'rate'

  def online_link(autoplay = true)
    return if show.online_link.blank?
    "#{show.online_link}?nocontrols=1&autoplay=#{autoplay ? 1 : 0}&season=#{season}&episode=#{number}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shows_genres
  has_many :shows, through: :shows_genres
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ApplicationRecord
  belongs_to :cacheable, :polymorphic => true
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :users_shows
  has_many :users, through: :users_shows
  has_many :episodes

  has_many :shows_genres
  has_many :genres, through: :shows_genres
  has_many :comments, :as => :commentable

  ratyrate_rateable 'rate'
end

app/models/shows_genre.rb
class ShowsGenre < ApplicationRecord
  belongs_to :show
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_shows
  has_many :shows, through: :users_shows
  has_many :users_episodes
  has_many :comments

  ratyrate_rater

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/users_episode.rb
class UsersEpisode < ApplicationRecord
  belongs_to :user
  belongs_to :episode
end

app/models/users_show.rb
class UsersShow < ApplicationRecord
  belongs_to :user
  belongs_to :show

  def self.select_by_status(status)
    select { |user_show| user_show.show_status == status }
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
    url = 'https://www.imdb.com/feature/genre/'
    doc = Nokogiri::HTML(open(url))
    doc.css('#main a').each do |item|
      next if item.text.blank?
      @new_genre = Genre.find_or_initialize_by(name: item.text)
      @new_genre.save
    end
    redirect_back fallback_location: root_path
  end

  def show
    @shows = Genre.find(params[:id]).shows.all.page(params[:page]).per(20)
    @current_genre = Genre.find(params[:id])
  end

  def index
    @all_genres = Genre.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def disclaimer; end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render json: true
    else
      render json: false
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :change_status]
  before_action :shows_list, only: [:index, :list]

  def index; end

  def show
    @show_genres = @show.genres
    @episodes = @show.episodes.where.not(released: nil).order(released: :desc).order(number: :desc)
    return if current_user.blank?
    @user_episodes = current_user.users_episodes.left_joins(:episode).where(episodes: { show: @show }).includes(:episode)
    @user_show = current_user.users_shows.find_by(show: @show) if current_user.present?
  end

  def change_status
    user_show = current_user.users_shows.find_or_initialize_by(show_id: @show.id)
    user_show.show_status = params[:status]
    user_show.save
    redirect_back fallback_location: root_path
  end

  def new
    Synchronizer.new.perform
    redirect_back fallback_location: root_path
  end

  def to_favorite
    user_show = current_user.users_shows.find_or_initialize_by(show_id: params[:id])
    user_show.show_status = :dont_watch unless user_show.id
    user_show.favorite = params[:favorite]
    user_show.save
    render json: :success
  end

  def list
    render action: 'index', layout: false
  end

  private

  def set_show
    @show = Show.find(params[:id])
  end

  def shows_list
    @shows = ShowSearch.new(params).results.page(params[:page]).per(20).includes(:genres)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    @users = User.all
  end

  def show
    @user_shows = @user.users_shows.includes(show: [:episodes, :rate_average])
    @user_episodes = @user.users_episodes.includes(episode: :show)
    @watching =      @user_shows.select_by_status('watching')
    @will_watch =    @user_shows.select_by_status('will_watch')
    @stopped_watch = @user_shows.select_by_status('stopped_watch')
    @favorites     = @user_shows.select(&:favorite?)
    @stats = {
      episodes: {
        count: @user_shows.sum {|u_s| u_s.show.episodes.size },
        watched: @user_episodes.count
      },
      hours: {
        count: @user_shows.sum { |u_s| u_s.show.episodes.size * u_s.show.runtime } / 60.0,
        watched: @user_episodes.sum { |u_e| u_e.episode.show.runtime } / 60.0
      },
      days: {
        count: @user_shows.sum { |u_s| u_s.show.episodes.size * u_s.show.runtime } / 60.0 / 24,
        watched: @user_episodes.sum { |u_e| u_e.episode.show.runtime } / 60.0 / 24
      }
    }

    @shows = Show.left_joins(:users_shows, :genres)
                 .where('shows.id NOT IN (?)', @user_shows.map(&:show_id))
                 .where('genres.id IN (?)', @user_shows.map(&:show).map(&:genres).flatten.map(&:id).uniq)
                 .order('rate_imdb DESC')
                 .distinct
                 .limit(6)
  end

  def favorites
    @shows = current_user.users_shows.where(favorite: true).map(&:show)
  end

  def rates
    @rated_shows = Array.new

    rate = Rate.where(:rater_id => current_user.id)
    rate.each {|rate|
      if rate.rateable_type == 'Show'
        @rated_shows.push(Show.find(rate.rateable_id))
      end
    }
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/index.html.haml
- content_for :title, (I18n.t 'header.genres-list')
.page
  .genres
    - @all_genres.each do |genre|
      %h6{align: 'center'}= link_to genre.name, genre

app/views/genres/show.html.haml
- content_for :title, (I18n.t 'show.genre') + ': ' + @current_genre.name

= render 'shows/list'

app/views/shows/_list.html.haml
.container.pt16
  .row
    - @shows.each do |show|
      .col-md-6
        .card.flex-md-row.mb-4.box-shadow.h-md-250
          = link_to show do
            = image_tag show.photo, class: 'card-img-left flex-auto d-none d-md-block'
          .card-body.d-flex.flex-column.align-items-start
            -#%strong.d-inline-block.mb-2.text-primary World
            %h3.mb-0
              = link_to show.name, show, class: 'text-dark'
            .mb-1.text-muted= show.genres.map(&:name).join(', ')
            %p.card-text.mb-auto= show.about[0..200] + (show.about.length > 300 ? '...' : '')
            = link_to (I18n.t 'read-more'), show

app/views/shows/index.html.haml
- content_for :title, (I18n.t 'header.shows-list')
= content_for :javascripts do
  = javascript_include_tag 'filter'

%form#form
  - unless params[:action] == 'list'
    .container.pt16
      .row
        .col-lg-3
          .form-group
            %label{for: 'search'}= I18n.t 'header.search'
            %input.form-control#name{name: 'name', type: 'text', value: params[:name]}
        .col-lg-3
          .form-group
            %label{for: 'order'} Сотрувати:
            %select#sort-by.form-control{name: 'order', value: params[:order]}
              %option{value: ''}
              %option{value: 'rate_desc', selected: (params[:order] == 'rate_desc')} По рейтингу за спаданням
              %option{value: 'rate_asc', selected: (params[:order] == 'rate_asc')} По рейтингу за зростанням
              %option{value: 'name_asc', selected: (params[:order] == 'name_asc')} По назві за зростанням
              %option{value: 'name_desc', selected: (params[:order] == 'name_desc')} По назві за спаданням
        .col-lg-3
          .form-group
            %label{for: 'sort-genre'} За жанром:
            %select#sort-genre.form-control{name: 'genre_id'}
              %option{value: ''}
              - Genre.all.each do |genre|
                %option{value: "#{genre.id}", selected: (params[:genre_id].to_i == genre.id)}= genre.name
        .col-lg-3
          .custom-control.custom-checkbox{style: 'padding-top: 28px'}
            %input.custom-control-input#online{type: 'checkbox', name: 'online', checked: params[:online]}
            %label.custom-control-label{for: 'online'} Перегляд онлайн
  #content
    = render partial: 'shows/list'

    .container
      = paginate @shows, params: { controller: 'shows', action: 'index' }

app/views/shows/show.html.haml
= content_for :title, @show.name + (@show.start_date ? "(#{@show.start_date&.year})" : '')
= content_for :javascripts do
  = javascript_include_tag 'jquery.raty'
  = javascript_include_tag 'ratyrate'
  = javascript_include_tag 'seasons-list'
  = javascript_include_tag 'favorite'

.container-fluid{style: 'background: #333; color: white; padding: 30px 0;'}
  .container
    .row
      .col-md-3
        = image_tag @show.photo, style: 'width: 100%'
        - if user_signed_in?
          %button.btn-watch-status.btn.btn-info.dropdown-toggle{type: :button, 'data-toggle': :dropdown, 'aria-haspopup': true, 'aria-expanded': false}
            - case @user_show&.show_status&.to_sym
              - when :watching
                = I18n.t 'user.watching'
              - when :will_watch
                = I18n.t 'user.will-watch'
              - when :stopped_watch
                = I18n.t 'user.stopped-watch'
              - else
                = I18n.t 'user.dont-watch'
          .dropdown-menu
            = link_to (I18n.t 'user.dont-watch'), change_status_show_path(@show, status: :dont_watch), class: 'dropdown-item'
            = link_to (I18n.t 'user.will-watch'), change_status_show_path(@show, status: :will_watch), class: 'dropdown-item'
            = link_to (I18n.t 'user.watching'), change_status_show_path(@show, status: :watching), class: 'dropdown-item'
            = link_to (I18n.t 'user.stopped-watch'), change_status_show_path(@show, status: :stopped_watch), class: 'dropdown-item'

          = link_to (I18n.t 'comment.add'), '#new_comment', class: 'btn-watch-comment btn btn-warning'

      .col-lg-9
        %h1.films-title
          .films-title-left
            = @show.name
            - if @show.start_date.present?
              %span.text-muted= "(#{@show.start_date.year})"
          - if current_user.present?
            .films-title-right
              %label.bookmarks{title: 'Мені подобається!', 'data-id': @show.id}
                %input{type: 'checkbox', checked: @user_show&.favorite}
                %span.bookmarks-status
        %h5
          - @show_genres.each do |genre|
            = link_to genre.name, shows_path(genre_id: genre.id), class: 'badge badge-info'

        %b= "#{t 'show.status'}:"
        %span.badge{class: "badge-#{@show.status == 'Run' ? 'success' : 'danger'}"}= @show.status
        %br
        %b= "#{t 'show.start-date'}:"
        = @show.start_date&.strftime('%d.%m.%Y')
        %br
        %b= "#{t 'show.finish-date'}:"
        = @show.finish_date&.strftime('%d.%m.%Y') || '...'
        %br
        %b= "#{t 'show.seasons'}:"
        = @show.seasons_count
        %br
        %b= "#{t 'show.runtime'}:"
        = "#{@show.runtime.to_s} min."
        %br
        %b= "#{t 'show.rate-imdb'}:"
        = @show.rate_imdb || 'Not rated yet'
        %br
        %b= 'Оцінка сайту:'
        = rating_for @show, 'rate', disable_after_rate: false, star_path: '/'
        %br
        %b= "#{t 'show.about'}:"
        = @show.about
        %br


- if @episodes.present?
  .container.pt16
    .row.justify-content-center
      .col-md-9
        .accordion#accordionSeason
          - count = @episodes.first.season
          - i = 0
          - while count > i do
            - current_season = @episodes.select { |episode| episode.season == count }
            .card
              .card-header.card-header-shows
                %h5.mb-0
                  %button.btn.btn-link{type: 'button', 'data-toggle': 'collapse', 'data-target': "#collapse-#{count}", 'aria-expanded': 'true', 'aria-controls': "collapse-#{count}"}= (I18n.t 'show.season') + ' ' + count.to_s
              .collapse.show{'aria-labelledby': 'heading-1', 'data-parent': '#accordionSeason', id: "collapse-#{count}"}
                .card-body
                  %table.table.table-striped
                    %tr
                      %th{width: '50px'}= '#'
                      %th{width: '530px'}= I18n.t 'show.name'
                      %th{width: '50px'}= I18n.t 'show.date'
                      %th
                      %th
                        - if current_user.present? && current_season.select { |e| e.released.past? }.present?  && @user_show && @user_show.show_status != 'dont_watch'
                          %label.watched.season{title: 'Переглянуто', 'data-id': current_season.map(&:id)}
                            %input{type: 'checkbox', checked: @user_episodes.select { |u_e| u_e.episode.season == count }.count == current_season.count}
                            %span.watched-status
                    - current_season.each do |episode|
                      %tr
                        %td= episode.season.to_s + 'x' + episode.number.to_s
                        %td= link_to episode.name, episode
                        %td
                          %span.badge{class: "badge-#{episode.released&.past? ? 'success' : 'secondary'}"}
                            = episode.released&.strftime('%d.%m.%Y')
                        %td
                          - if @show.online_link.present? && episode.released.past?
                            %span.toggle-films{'data-src': episode.online_link}
                        %td
                          - if current_user.present? && episode.released.past? && @user_show && @user_show.show_status != 'dont_watch'
                            %label.watched.episode{title: 'Переглянуто', 'data-id': [episode.id]}
                              %input{type: 'checkbox', checked: @user_episodes.select { |u_e| u_e.episode_id == episode.id }.present? }
                              %span.watched-status
                      - if @show.online_link.present? && episode.released.past?
                        %tr.film-ct
                          %td{colspan: 5}
                            .films-inner-ct

              - count -= 1

      .col-md-9
        = render partial: 'comments/comments', locals: { parent: @show }

app/views/users/_shows_list.html.haml
.watching-time
  %p.watching-name= title
  %span.dots
  %p.watching-current &nbsp;
%ul.serials-list
  - shows.each do |show|
    - episodes_count = show.episodes.size
    - watched_count = @user.users_episodes.joins(episode: :show).where(shows: { id: show.id }).count
    %li.serials-list-item
      .serials-link
        = link_to show do
          = show.name
          %span.badge{class: "badge-#{show.status == 'Run' ? 'success' : 'danger'}"}= show.status
      .serials-stars
        = rating_for show, 'rate', disable_after_rate: false, star_path: '/'
      .serials-progress
        .serials-progress-header
          %span &nbsp;
          %span= episodes_count
        .serials-progress-outer
          .serials-progress-inner{style: "width: #{watched_count * 100 / episodes_count.to_f}%"}
            %span= watched_count

app/views/users/favorites.html.haml
- content_for :title, (I18n.t 'user.favorites')

= render 'shows/list'

app/views/users/index.html.haml
- content_for :title, (I18n.t 'header.users-list')
.page.show-list
  %ul.large-block-grid-4
    - @users.each do |user|
      %li
        .user-avatar
          = image_tag user.avatar.url(:medium)
          .blocks-names= link_to user.login, user

app/views/users/rates.html.haml
- content_for :title, (I18n.t 'user.rates')
.page
  %table.rated
    %tr
      %th{:width => '50px'}
        %strong= I18n.t 'user.mark'
      %th{:width => '530px'}
        %strong= I18n.t 'show.name'
    - @rated_shows.each do |show|
      %tr
        %td= rating_for_user show, current_user, "rate"
        %td= link_to show.name, show

app/views/users/show.html.haml
- content_for :title, @user.login
= content_for :javascripts do
  = javascript_include_tag 'jquery.raty'
  = javascript_include_tag 'ratyrate'

.container.pt16
  .row
    .col-md-3
      .user-avatar
        = image_tag @user.avatar.url(:medium)
      - if user_signed_in?
        - if current_user.access == 1 && @user == current_user
          .user-drop
            %button{type: 'button', class: 'btn btn-info dropdown-toggle', 'data-toggle': 'dropdown', 'aria-haspopup': 'true', 'aria-expanded': 'false'}
              = I18n.t 'user.site-control'
            .dropdown-menu
              = link_to (I18n.t 'user.parse'), new_show_path, class: 'dropdown-item'
              -#= link_to (I18n.t 'user.parse-genres'), new_genre_path, class: 'dropdown-item'
              -#= link_to (I18n.t 'user.parse-episodes'), new_episode_path, class: 'dropdown-item'
              = link_to (I18n.t 'user.admin-panel'), rails_admin_path, class: 'dropdown-item'

    .col-md-9
      .box-ct
        .box-item.box-red
          .stats
            %p= @stats[:episodes][:watched]
            %p= t('user.episodes')
          %b{style: "height: #{@stats[:episodes][:watched] * 100.0 / @stats[:episodes][:count]}%"}
        .box-item.box-green
          .stats
            %p= @stats[:hours][:watched].round(1)
            %p= t('user.hours')
          %b{style: "height: #{@stats[:hours][:watched] * 100.0 / @stats[:hours][:count]}%"}
        .box-item.box-blue
          .stats
            %p= @stats[:days][:watched].round(1)
            %p= t('user.days')
          %b{style: "height: #{@stats[:days][:watched] * 100.0 / @stats[:days][:count]}%"}
    .col-md-12.pt16
      %ul.nav.nav-tabs.nav-history{role: 'tablist'}
        %li.nav-item
          %a.nav-link.active{'data-toggle': 'tab', href: '#watching', 'role': 'tab'}
            = t('user.watching')
            = "(#{@watching.count})"
        %li.nav-item
          %a.nav-link{'data-toggle': 'tab', href: '#going_to_watch', 'role': 'tab'}
            = t('user.will-watch')
            = "(#{@will_watch.count})"
        %li.nav-item
          %a.nav-link{'data-toggle': 'tab', href: '#stopped_watch', 'role': 'tab'}
            = t('user.stopped-watch')
            = "(#{@stopped_watch.count})"
        %li.nav-item
          %a.nav-link{'data-toggle': 'tab', href: '#favorites', 'role': 'tab'}
            = t('user.favorites')
            = "(#{@favorites.count})"
      .tab-content
        .tab-pane.fade.show.active#watching
          = render partial: 'shows_list', locals: { shows: @watching.map(&:show), title: t('user.watching') }
        .tab-pane.fade#going_to_watch
          = render partial: 'shows_list', locals: { shows: @will_watch.map(&:show), title: t('user.will-watch') }
        .tab-pane.fade#stopped_watch
          = render partial: 'shows_list', locals: { shows: @stopped_watch.map(&:show), title: t('user.stopped-watch') }
        .tab-pane.fade#favorites
          = render partial: 'shows_list', locals: { shows: @favorites.map(&:show), title: t('user.favorites') }

    - if @shows.present?
      .col-md-12
        %h3 Рекомендації
        = render 'shows/list'