config/routes.rb
Rails.application.routes.draw do
  authenticated :user, ->(user) { user.access } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: { registrations: 'devise_override/registrations' }

  root to: 'shows#index'

  resources :shows do
    get :list, on: :collection
    get :change_status, on: :member
    post :to_favorite, on: :member
    resources :comments
  end

  resources :genres

  resources :users do
    get :favorites, on: :member
    get :rates, on: :member
  end

  resources :comments, only: [:create]
  resources :episodes, only: [:new, :show] do
    resources :comments
    post :mark_as_watched, on: :collection
  end

  get :what_to_see, to: 'episodes#what_to_see'
  get :disclaimer, to: 'home#disclaimer'

  post '/rate' => 'rater#create', as: 'rate'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, :polymorphic => true
  has_many :comments, as: :commentable
  belongs_to :user

  validates_presence_of :body, :user, :commentable

  def show
    return @show if defined?(@show)
    @post = commentable.is_a?(Show) ? commentable : commentable.show
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :show
  has_many :users_episodes
  has_many :comments, :as => :commentable

  ratyrate_rateable 'rate'

  def online_link(autoplay = true)
    return if show.online_link.blank?
    "#{show.online_link}?nocontrols=1&autoplay=#{autoplay ? 1 : 0}&season=#{season}&episode=#{number}"
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :shows_genres
  has_many :shows, through: :shows_genres
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ApplicationRecord
  belongs_to :cacheable, :polymorphic => true
end

app/models/show.rb
class Show < ApplicationRecord
  has_many :users_shows
  has_many :users, through: :users_shows
  has_many :episodes

  has_many :shows_genres
  has_many :genres, through: :shows_genres
  has_many :comments, :as => :commentable

  ratyrate_rateable 'rate'
end

app/models/shows_genre.rb
class ShowsGenre < ApplicationRecord
  belongs_to :show
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_shows
  has_many :shows, through: :users_shows
  has_many :users_episodes
  has_many :comments

  ratyrate_rater

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/users_episode.rb
class UsersEpisode < ApplicationRecord
  belongs_to :user
  belongs_to :episode
end

app/models/users_show.rb
class UsersShow < ApplicationRecord
  belongs_to :user
  belongs_to :show

  def self.select_by_status(status)
    select { |user_show| user_show.show_status == status }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def disclaimer; end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render json: true
    else
      render json: false
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :change_status]
  before_action :shows_list, only: [:index, :list]

  def index; end

  def show
    @show_genres = @show.genres
    @episodes = @show.episodes.where.not(released: nil).order(released: :desc).order(number: :desc)
    return if current_user.blank?
    @user_episodes = current_user.users_episodes.left_joins(:episode).where(episodes: { show: @show }).includes(:episode)
    @user_show = current_user.users_shows.find_by(show: @show) if current_user.present?
  end

  def change_status
    user_show = current_user.users_shows.find_or_initialize_by(show_id: @show.id)
    user_show.show_status = params[:status]
    user_show.save
    redirect_back fallback_location: root_path
  end

  def new
    Synchronizer.new.perform
    redirect_back fallback_location: root_path
  end

  def to_favorite
    user_show = current_user.users_shows.find_or_initialize_by(show_id: params[:id])
    user_show.show_status = :dont_watch unless user_show.id
    user_show.favorite = params[:favorite]
    user_show.save
    render json: :success
  end

  def list
    render action: 'index', layout: false
  end

  private

  def set_show
    @show = Show.find(params[:id])
  end

  def shows_list
    @shows = ShowSearch.new(params).results.page(params[:page]).per(20).includes(:genres)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    = link_to 'Правовласникам', disclaimer_path, class: 'text-muted'
    %i.pull-right Copyright (c) 2018

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.fixed-top.bg-dark
  .container
    = link_to 'TVshows', root_path, class: 'navbar-brand'
    %button.navbar-toggler{'aria-expanded': false, 'data-toggle': 'collapse', type: :button}
      %span.navbar-toggler-icon
    #navbarsExample07.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        -#%li.nav-item.active
        -#  %a.nav-link{:href => "#"}
        -#    Home
        -#    %span.sr-only (current)
        %li.nav-item= link_to (I18n.t 'header.shows-list'), shows_path, class: 'nav-link'
        -#%li.nav-item= link_to (I18n.t 'header.genres-list'), genres_path, class: 'nav-link'
        - if user_signed_in?
          %li.nav-item= link_to 'Що подивитись?', what_to_see_path, class: 'nav-link'
        -#%li.nav-item= link_to (I18n.t 'header.users-list'), users_path, class: 'nav-link'
        -#%li.nav-item
        -#  %a.nav-link.disabled{:href => "#"} Disabled

      - if user_signed_in?
        %li.nav-item.dropdown.form-inline.my-2.my-md-0
          %a.account-toggle.nav-link.dropdown-toggle{'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': :dropdown, href: '#'}
            .account-info.d-none.d-sm-block
              %p.text-truncate= current_user.login
            .header-avatar
              = image_tag current_user.avatar.url(:thumb)
          .dropdown-menu
            = link_to (I18n.t 'header.profile'), current_user, class: 'dropdown-item'
            = link_to (I18n.t 'user.edit-profile'), edit_user_registration_path(current_user), class: 'dropdown-item'
            = link_to (I18n.t 'user.favorites'), favorites_user_path(current_user), class: 'dropdown-item'
            = link_to (I18n.t 'header.logout'), destroy_user_session_path, class: 'dropdown-item', method: :delete
      - else
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to (I18n.t 'header.sign-in'), new_user_session_path, class: 'nav-link'
          %li.nav-item
            = link_to (I18n.t 'header.sign-up'), new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.haml
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'TVshows'
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width', 'initial-scale': '1.0'}
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600&subset=latin,cyrillic'
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
  %body
    = render partial: 'layouts/header'
    .wrapper
      = yield
    = render 'layouts/footer'

  = javascript_include_tag 'application'
  = yield :javascripts